import { Link } from 'react-router-dom'
import useMavraLanguage from '../components/useMavraLanguage.js'
import { EvidenceLayout, VisualEvidence, AssetNote } from '../components/CaseEvidence.jsx'
import { candleAplus } from '../content/caseEvidence.js'
export default function AplusBriefs(){const [lang]=useMavraLanguage();const es=lang==='es';return <EvidenceLayout title={es?'A+: del set de velas a una colección.':'A+: from a candle set to a collection.'} intro={es?'A+ es el contenido visual ampliado de una ficha de Amazon. Aquí recuperamos el brief del Skull Candle Set: una secuencia de seis módulos para presentar el producto, explicar sus detalles y mostrar cómo encaja en un hogar.':'A+ is the enhanced visual content on an Amazon product page. Here is the recovered Skull Candle Set brief: six modules introducing the product, explaining its details and showing its place in a home.'}>
 <section className="editorial-section"><p className="editorial-status">{es?'Entregable: secuencia y copy del brief A+':'Deliverable: A+ sequence and brief copy'}</p><div className="editorial-split"><VisualEvidence indices={[1]}/><div><h2>{es?'La decisión: mostrar una colección en uso.':'The decision: show a collection in use.'}</h2><p>{es?'El brief sustituye una tabla comparativa por tres estados de la misma habitación: primero las velas, después los cráneos de pared y finalmente la lámpara. Así, la relación entre los productos se explica visualmente.':'The brief replaces a comparison table with three states of the same room: candles first, wall skulls next, then the lamp. The relationship between the products is explained visually.'}</p><p>{es?'El entregable define el orden de los módulos, la escena y el mensaje que acompaña cada paso.':'The deliverable defines the module order, setting and message at each step.'}</p><AssetNote/></div></div></section>
 <section className="editorial-section" id="modules"><h2>{es?'La secuencia del Skull Candle Set':'The Skull Candle Set sequence'}</h2><p>{es?'Este es el contenido específico del brief, no una maqueta de la interfaz de Amazon. Los archivos exportados de los seis módulos no están disponibles en este archivo público.':'This is the specific brief content, not a mock-up of Amazon’s interface. The six exported module files are not available in this public archive.'}</p><ol className="module-sequence">{candleAplus.map((m,i)=><li key={m[0]}><span className="module-number">{String(i+1).padStart(2,'0')}</span><div><h3>{m[es?1:0]}</h3><p>{m[es?4:3]}</p>{m[2]&&<blockquote>{m[2]}</blockquote>}<p className="editorial-note"><strong>{es?'Para el comprador: ':'For the buyer: '}</strong>{m[es?6:5]}</p></div></li>)}</ol><details className="brief-slot"><summary>{es?'Preguntas previstas en el bloque de texto':'Questions planned for the text block'}</summary><ul>{(es?['¿Qué material tiene?','¿Qué tamaño tienen las piezas?','¿Es solo para Halloween?','¿Cómo es el aroma?','¿Se puede regalar?']:['What is it made of?','How large are the pieces?','Is it only for Halloween?','What does it smell like?','Can I give it as a gift?']).map(q=><li key={q}>{q}</li>)}</ul><p>{es?'El brief contempla estas preguntas aparte de la secuencia visual.':'The brief plans these questions separately from the visual sequence.'}</p></details></section>
 <section className="editorial-section"><h2>{es?'La misma lógica, aplicada al resto de la marca':'The same logic across the brand'}</h2><p>{es?'Wall Skulls: instalación → relieve → escala → habitación → colección. Skull Lamp: efecto de luz → opciones de pantalla → tamaño → uso. Son recorridos definidos en el brief.':'Wall Skulls: installation → depth → scale → room → collection. Skull Lamp: light effect → shade options → size → use. These sequences are defined in the brief.'}</p><div className="editorial-links"><Link to="/listings-briefs">{es?'Examinar los briefs por producto':'Inspect briefs by product'} →</Link><Link to="/briefing">{es?'Ver la dirección creativa':'See the creative direction'} →</Link></div></section>
 </EvidenceLayout>}
