import { Link } from 'react-router-dom'
import useMavraLanguage from '../components/useMavraLanguage.js'
import { EvidenceLayout } from '../components/CaseEvidence.jsx'
const copy={es:{title:'Qué hace reconocible a MAVRA.',intro:'El Brand Book reúne las decisiones sobre comprador, posicionamiento, lenguaje e identidad visual. Este resumen explica cinco decisiones y enlaza al apartado completo que las desarrolla.',items:[
 ['El hogar como expresión personal','La estrategia se dirige a personas que quieren decoración oscura todo el año. El producto debe encajar en su espacio cotidiano, no depender de una celebración.','Leer el análisis del consumidor','/brand-guidelines/source#d1'],
 ['Decoración permanente','El territorio elegido es el interior oscuro permanente. Ese criterio orienta escenas, materiales y mensajes.','Leer el posicionamiento','/brand-guidelines/source#d2-territory'],
 ['Una voz reconocible','La plataforma define qué representa la marca y cómo expresa esa identidad con palabras y productos.','Leer la plataforma de marca','/brand-guidelines/source#d3'],
 ['Luz, contraste y objeto','La identidad visual prioriza luz cálida controlada, contraste y detalle del producto. Las reglas permiten repetir la dirección sin repetir cada imagen.','Leer las reglas visuales','/brand-guidelines/source#d4'],
 ['De la identidad al uso','La guía conecta la marca con sus aplicaciones: contenido de producto, escenas y comunicación.','Ver las aplicaciones previstas','/brand-guidelines/source#d5']
 ],source:'Abrir el Brand Book completo',visual:'Ver ejemplos de dirección creativa'},en:{title:'What makes MAVRA recognisable.',intro:'The Brand Book brings together choices about the customer, positioning, language and visual identity. This summary explains five decisions and links to the full section behind each.',items:[
 ['The home as self-expression','The strategy addresses people who want dark decor throughout the year. The product should fit their everyday space rather than depend on a celebration.','Read the customer analysis','/brand-guidelines/source#d1'],
 ['Permanent decor','The chosen territory is the permanent dark interior. That choice guides settings, materials and messages.','Read the positioning','/brand-guidelines/source#d2-territory'],
 ['A recognisable voice','The platform defines what the brand represents and how it expresses that identity through words and products.','Read the brand platform','/brand-guidelines/source#d3'],
 ['Light, contrast and the object','The visual identity prioritises controlled warm light, contrast and product detail. The rules make the direction repeatable without repeating every image.','Read the visual rules','/brand-guidelines/source#d4'],
 ['From identity to application','The guide connects the brand to its applications: product content, settings and communication.','See the planned applications','/brand-guidelines/source#d5']
 ],source:'Open the complete Brand Book',visual:'See examples of creative direction'}}
export default function BrandGuidelines(){const [lang]=useMavraLanguage();const t=copy[lang];return <EvidenceLayout title={t.title} intro={t.intro}><section className="editorial-section"><ol className="module-sequence">{t.items.map(([h,p,l,to],i)=><li key={to}><span className="module-number">0{i+1}</span><div><h2>{h}</h2><p>{p}</p><div className="editorial-links"><Link to={to}>{l} →</Link></div></div></li>)}</ol><div className="editorial-links"><Link to="/brand-guidelines/source">{t.source} →</Link><Link to="/briefing">{t.visual} →</Link></div></section></EvidenceLayout>}
