import { Link } from 'react-router-dom'
import useMavraLanguage from '../components/useMavraLanguage.js'
import { EvidenceLayout, VisualEvidence } from '../components/CaseEvidence.jsx'
export default function Briefing(){const [lang]=useMavraLanguage();const es=lang==='es';const rows=es?[
 ['Relieve antes que adorno','El primer plano del cráneo utiliza luz lateral para hacer visible el volumen.','En el brief de listing, la imagen de detalle responde si el producto es una escultura o una placa.','/listings-briefs#wall-skulls','Ver la secuencia de Wall Skulls'],
 ['La luz explica el producto','La llama revela el acabado y convierte el set en un objeto de uso, no solo de decoración.','En A+, apertura, vídeo y detalles explican el set antes de ampliar la escena a toda la habitación.','/aplus-briefs#modules','Ver los seis módulos A+'],
 ['Una habitación conecta la colección','La lámpara comparte con las velas luz cálida, fondos oscuros y atención al objeto.','El brief de A+ combina los tres productos por etapas. El archivo Pinterest traslada ese mismo mundo a piezas individuales.','/pinterest','Ver las piezas de Pinterest']
]:[
 ['Depth before decoration','The skull close-up uses side lighting to reveal its volume.','In the listing brief, the detail image answers whether the product is a sculpture or a flat plaque.','/listings-briefs#wall-skulls','See the Wall Skulls sequence'],
 ['Light explains the product','The flame reveals the finish and shows the set in use, beyond decoration.','In A+, the opening, video and detail modules explain the set before expanding into the room.','/aplus-briefs#modules','See the six A+ modules'],
 ['One room connects the collection','The lamp shares warm light, dark settings and a focus on the object with the candles.','The A+ brief combines the products in stages. The Pinterest archive carries the same world into individual pieces.','/pinterest','See the Pinterest pieces']
];return <EvidenceLayout id="briefing-top" title={es?'Una dirección visual que se puede reconocer.':'A visual direction you can recognise.'} intro={es?'Tres piezas existentes del archivo Pinterest permiten ver las decisiones: luz controlada, detalle del objeto y espacios que se sienten habitados. Debajo de cada una explicamos cómo esa regla se traslada a los briefs de Amazon.':'Three existing pieces from the Pinterest archive make the choices visible: controlled light, object detail and lived-in spaces. Below each, we explain how that rule carries into the Amazon briefs.'}>
 <section className="editorial-section"><div className="creative-comparison">{rows.map((r,i)=><article key={r[0]}><VisualEvidence indices={[i]}/><h2>{r[0]}</h2><p>{r[1]}</p><p className="editorial-note">{r[2]}</p><Link to={r[3]}>{r[4]} →</Link></article>)}</div></section>
 <section className="editorial-section"><h2>{es?'Lo que se mantiene en cada pieza':'What stays consistent in every piece'}</h2><div className="editorial-facts">{(es?[
 ['Producto','La silueta y el detalle del objeto son el centro de la composición.'],['Luz','Una luz cálida dominante hace legible el objeto dentro del ambiente oscuro.'],['Contexto','Materiales y espacios cotidianos expresan decoración permanente, no una escena de Halloween.']
 ]:[['Product','The object’s silhouette and detail remain central to the composition.'],['Light','One dominant warm light makes the object readable within a dark setting.'],['Context','Materials and everyday spaces express permanent decor, rather than a Halloween scene.']]).map(([h,p])=><article key={h}><h3>{h}</h3><p>{p}</p></article>)}</div><p className="editorial-note">{es?'Las imágenes mostradas son piezas del archivo Pinterest, no exportaciones de Amazon. La comparación demuestra decisiones visuales compartidas; no resultados de conversión.':'The images shown are Pinterest archive pieces, not Amazon exports. The comparison demonstrates shared visual choices, not conversion results.'}</p></section>
 <section className="editorial-section"><h2>{es?'Profundiza en las reglas de producción':'Explore the production rules'}</h2><div className="editorial-links"><Link to="/scenography#scenography-top">{es?'Escenarios, luz y cámara':'Settings, light and camera'} →</Link><Link to="/filmografia">{es?'Dirección de vídeo':'Video direction'} →</Link><Link to="/avatares">{es?'Personas y vestuario':'People and wardrobe'} →</Link><Link to="/brand-guidelines">{es?'Decisiones de marca':'Brand decisions'} →</Link></div></section>
 </EvidenceLayout>}
