import { Link } from 'react-router-dom'
import useMavraLanguage from '../components/useMavraLanguage.js'
import '../case-editorial.css'
const CONTENT={
 es:{title:'Explora el trabajo detrás de MAVRA.',intro:'Brand OS es el archivo del caso: documentos de marca, briefs creativos y herramientas de planificación. Elige qué quieres examinar; cada enlace indica lo que encontrarás.',back:'Leer el caso primero',groups:[
 ['Marca y dirección visual','Cómo definimos la marca y las reglas para producir imágenes coherentes.',[['Decisiones de marca','/brand-guidelines'],['Brand Book completo','/brand-guidelines/source'],['Referentes culturales','/corrientes'],['Tipografía','/fonts'],['Piezas y dirección creativa','/briefing#briefing-top'],['Guía de escenarios y luz','/scenography#scenography-top'],['Dirección de vídeo','/filmografia'],['Personas y vestuario','/avatares']]],
 ['Contenido de producto','Qué contamos y mostramos para ayudar al comprador a elegir.',[['Los tres productos','/skulls'],['20 briefs de imagen','/listings-briefs'],['Secuencia y copy A+','/aplus-briefs'],['Textos y palabras clave de producto','/copy']]],
 ['Investigación y lanzamiento','Las herramientas para estudiar oportunidades y organizar la ejecución.',[['Demanda y palabras clave','/research'],['Comparación de competidores','/competitors'],['Plan de publicidad en Amazon','/campaigns'],['Comprobaciones de lanzamiento','/launch'],['Piezas y plan de Pinterest','/pinterest'],['Estrategia de creadores','/influencers'],['Brief para colaboradores','/creators']]]
 ],contact:'Hablemos de tu marca'},
 en:{title:'Explore the work behind MAVRA.',intro:'Brand OS is the case archive: brand documents, creative briefs and planning tools. Choose what you want to inspect; each link tells you what you will find.',back:'Read the case first',groups:[
 ['Brand and visual direction','How we defined the brand and the rules for producing consistent imagery.',[['Brand decisions','/brand-guidelines'],['Complete Brand Book','/brand-guidelines/source'],['Cultural references','/corrientes'],['Typography','/fonts'],['Creative pieces and direction','/briefing#briefing-top'],['Setting and lighting guide','/scenography#scenography-top'],['Video direction','/filmografia'],['People and wardrobe','/avatares']]],
 ['Product content','What we explain and show to help shoppers choose.',[['The three products','/skulls'],['20 image briefs','/listings-briefs'],['A+ sequence and copy','/aplus-briefs'],['Product copy and keywords','/copy']]],
 ['Research and launch','Tools for reviewing opportunities and organising execution.',[['Search demand and keywords','/research'],['Competitor comparison','/competitors'],['Amazon advertising plan','/campaigns'],['Launch checks','/launch'],['Pinterest creative and plan','/pinterest'],['Creator strategy','/influencers'],['Collaborator brief','/creators']]]
 ],contact:'Let’s talk about your brand'}
}
export default function Home(){const [lang]=useMavraLanguage();const t=CONTENT[lang];return <main className="case-study editorial-case"><header className="editorial-header"><p className="case-eyebrow">AGTA / MAVRA · Brand OS</p><h1>{t.title}</h1><p className="editorial-lead">{t.intro}</p><div className="editorial-links"><Link to="/">← {t.back}</Link></div></header><section className="editorial-section editorial-library-grid" aria-label="Brand OS">{t.groups.map(([title,body,links])=><article key={title}><h2>{title}</h2><p>{body}</p><nav className="editorial-links" aria-label={title}>{links.map(([label,to])=><Link key={to} to={to}>{label} →</Link>)}</nav></article>)}</section><footer className="editorial-footer"><Link to="/">← {t.back}</Link><Link to="/#contact">{t.contact} →</Link></footer></main>}
