import useMavraLanguage from '../components/useMavraLanguage.js'
import { EvidenceLayout, VisualEvidence, AssetNote } from '../components/CaseEvidence.jsx'
import { listingBriefs } from '../content/caseEvidence.js'
import { Link } from 'react-router-dom'
export default function Listings(){
 const [lang]=useMavraLanguage();const es=lang==='es'
 return <EvidenceLayout title={es?'Cada imagen responde una pregunta de compra.':'Every image answers a buying question.'} intro={es?'El listing es la ficha de producto en Amazon. Estos briefs definen qué debe mostrar cada imagen, qué duda resuelve y qué mensaje la acompaña, para las tres líneas de MAVRA.':'A listing is the product page on Amazon. These briefs define what each image should show, the question it answers and its message, across MAVRA’s three product lines.'}>
 <section className="editorial-section"><p className="editorial-status">{es?'Entregable: brief de imágenes · 20 posiciones documentadas':'Deliverable: image brief · 20 documented slots'}</p><AssetNote/><nav className="editorial-jump" aria-label={es?'Elegir producto':'Choose a product'}>{listingBriefs.map(p=><a key={p.id} href={'#'+p.id}>{p.name}</a>)}</nav></section>
 {listingBriefs.map((p,i)=><section className="editorial-section" id={p.id} key={p.id}><h2>{p.name}</h2><div className="brief-product"><VisualEvidence indices={[i]}/><div><p className="editorial-note">{es?'Secuencia recuperada del brief de producción. El texto destinado al comprador estadounidense se conserva en inglés. Las especificaciones y la elegibilidad de las imágenes deben verificarse antes de publicarlas.':'Sequence recovered from the production brief. Copy intended for US shoppers remains in English. Product specifications and image eligibility need verification before publication.'}</p>{p.slots.map((s,n)=><details className="brief-slot" key={s[0]} open={n===0||n===1}><summary><span>{String(n+1).padStart(2,'0')}</span> {s[es?1:0]}</summary><dl><dt>{es?'Pregunta del comprador':'Buyer question'}</dt><dd>{s[es?5:4]}</dd><dt>{es?'Decisión de imagen':'Image direction'}</dt><dd>{s[es?3:2]}</dd>{s[6]&&<><dt>{es?'Texto del brief · Amazon US':'Brief copy · Amazon US'}</dt><dd className="brief-copy">{s[6]}</dd></>}</dl></details>)}</div></div></section>)}
 <section className="editorial-section"><h2>{es?'Del mensaje a la ficha completa':'From the message to the complete product page'}</h2><p>{es?'Las imágenes aclaran uso, escala y materiales. El texto desarrolla la información del producto; A+ organiza el recorrido visual de la marca.':'Images clarify use, scale and materials. Copy develops product information; A+ organises the brand’s visual story.'}</p><div className="editorial-links"><Link to="/copy">{es?'Ver textos de producto':'See product copy'} →</Link><Link to="/aplus-briefs">{es?'Ver el brief A+':'See the A+ brief'} →</Link></div></section>
 </EvidenceLayout>
}
